site_name: Acquia BLT Documentation

repo_url: https://github.com/acquia/blt
edit_uri: edit/9.x/docs/
site_description: 'BLT - Acquia Build & Launch Tools'
theme:
  name: readthedocs
strict: true

extra_javascript:
  - js/fix_search.js

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
