site_name: Acquia BLT Documentation

repo_url: https://github.com/acquia/blt
site_description: 'BLT - Acquia Build & Launch Tools'
theme: readthedocs
strict: true

extra_javascript:
  - readme/js/fix_search.js

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
  - Overview: 'README.md'
  - Getting started:
    - Installation:
       - System requirements:  'INSTALL.md'
       - Running BLT in Ubuntu on Bash on Windows: 'readme/windows-install.md'
       - Alternative LAMP stacks: 'readme/local-development.md'
    - Create a new project: 'readme/creating-new-project.md'
    - Add to existing project: 'readme/adding-to-project.md'
    - Next steps: 'readme/next-steps.md'
    - Updating BLT: 'readme/updating-blt.md'
  - Project documentation:
    - Developer:
          - Onboarding: 'readme/onboarding.md'
          - Required / Recommended Skills: 'readme/skills.md'
          - Repository architecture: 'readme/repo-architecture.md'
          - Running project tasks:
            - Overview: 'readme/project-tasks.md'
            - Dependency management: 'readme/dependency-management.md'
            - Patches: 'template/patches/README.md'
            - Drush: 'template/drush/README.md'
            - Git hooks: 'scripts/git-hooks/README.md'
          - Development Workflow: 'readme/dev-workflow.md'
          - Configuration Management: 'readme/configuration-management.md'
          - Automated testing: 'readme/testing.md'
    - Technical Architect:
        - Deploying to cloud: 'readme/deploy.md'
        - Release process: 'readme/release-process.md'
        - Setting up continuous integration: 'readme/ci.md'
        - Setting up SSO with SimpleSAMLphp: 'readme/simplesamlphp-setup.md'
        - Setting up multisite: 'readme/multisite.md'
        - Open source contribution: 'readme/os-contribution.md'
  - Extending / Overriding BLT: 'readme/extending-blt.md'
  - Support & Contribution: 'CONTRIBUTING.md'
