name: Merge dependency updates
on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "ORCA CI"
jobs:
  merge:
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.actor.login == 'violinist-bot'
    steps:
    - name: "Get PR information"
      uses: potiuk/get-workflow-origin@v1_3
      id: source-run-info
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        sourceRunId: ${{ github.event.workflow_run.id }}
    - run: 'gh pr merge --squash https://github.com/acquia/blt/pull/${{ env.GITHUB_PR }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PR: ${{ steps.source-run-info.outputs.pullRequestNumber }}
  update_release_draft:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
