name: Merge dependency updates
on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "ORCA CI"
jobs:
  merge:
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.actor.login == 'violinist-bot'
    steps:
    - run: 'gh pr merge --squash https://github.com/acquia/blt/pull/${{ env.GITHUB_PR }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PR: ${{ github.event.workflow_run.pull_requests[0].number }}
  update_release_draft:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
